# 1 查看一级领域及论文数量

In [5]:
from tqdm import tqdm 
import pandas as pd 

field_list = [] 

with open('/home/Dataset/MAG/mag_20211108/advanced/FieldsOfStudy.txt', 'r') as fp:
    for line in tqdm(fp):
        columns = line.split('\t')
        id = int(columns[0])
        field_name = columns[3].strip() 
        level = int(columns[5])
        paper_count = int(columns[6])
        
        if level == 0:
            field_list.append(
                dict(
                    id = id, 
                    field_name = field_name,
                    paper_count = paper_count, 
                )
            )

field_list.sort(key=lambda x: -x['paper_count'])

pd.DataFrame({
    'ID': [x['id'] for x in field_list],
    'Field Name': [x['field_name'] for x in field_list],
    'Paper Count': [x['paper_count'] for x in field_list],
})

714856it [00:01, 646255.84it/s]

           ID             Field Name  Paper Count
0   192562407      Materials science     31648329
1    71924100               Medicine     29889930
2    41008148       Computer science     27910093
3   185592680              Chemistry     18840345
4    86803240                Biology     14132398
5   127413603            Engineering     12728053
6   121332964                Physics      9398685
7    15744967             Psychology      8465886
8   127313418                Geology      7497214
9    33923547            Mathematics      7181874
10   17744445      Political science      6985258
11   39432304  Environmental science      6462273
12  144133560               Business      5643910
13  205649164              Geography      4635445
14  144024400              Sociology      4606292
15  142362112                    Art      3897460
16  162324750              Economics      3214420
17   95457728                History      3119899
18  138885662             Philosophy      2047027

# 2 查看二级领域及论文数量

In [6]:
TOP_FIELD_ID = 41008148

field_id_set = set()  

with open('/home/Dataset/MAG/mag_20211108/advanced/FieldOfStudyChildren.txt', 'r') as fp:
    for line in tqdm(fp):
        columns = line.split('\t')
        field_id = int(columns[0])
        child_field_id = int(columns[1])

        if field_id == TOP_FIELD_ID:
            field_id_set.add(child_field_id)

field_list = [] 

with open('/home/Dataset/MAG/mag_20211108/advanced/FieldsOfStudy.txt', 'r') as fp:
    for line in tqdm(fp):
        columns = line.split('\t')
        field_id = int(columns[0])
        field_name = columns[3].strip() 
        field_level = int(columns[5])
        paper_count = int(columns[6])
        
        if field_id in field_id_set:
            assert field_level == 1 
            
            field_list.append(
                dict(
                    field_id = field_id, 
                    field_name = field_name,
                    paper_count = paper_count, 
                )
            )

field_list.sort(key=lambda x: -x['paper_count'])

print(f"二级领域总数：{len(field_list)}")

pd.DataFrame({
    'ID': [x['field_id'] for x in field_list],
    'Field Name': [x['field_name'] for x in field_list],
    'Paper Count': [x['paper_count'] for x in field_list],
})

840110it [00:00, 1262574.68it/s]
714856it [00:01, 673685.31it/s]

二级领域总数：34

            ID                    Field Name  Paper Count
0    154945302       Artificial intelligence      4644259
1     31972630               Computer vision      2333963
2     31258907              Computer network      2156670
3      9390403             Computer hardware      2153911
4     11413529                     Algorithm      1626998
5    161191863               Library science      1585961
6    136764020                World Wide Web      1091870
7     44154836                    Simulation      1028638
8     79403827           Real-time computing       987375
9     56739046          Knowledge management       911897
10   178980831           Pattern recognition       908484
11    49774154                    Multimedia       886245
12   124101348                   Data mining       762302
13    38652104             Computer security       717900
14    23123220         Information retrieval       641017
15   121684516    Computer graphics (images)       609735
16    77088390                      Database       575106
17   107457646    Human–computer interaction       557190
18   120314980         Distributed computing       550404
19   119857082              Machine learning       535862
20  2522767166                  Data science       531797
21    76155785            Telecommunications       514986
22    28490314            Speech recognition       504980
23   149635348               Embedded system       487889
24    80444323  Theoretical computer science       458401
25   204321447   Natural language processing       454966
26   111919701              Operating system       405960
27   115903868          Software engineering       368585
28   199360897          Programming language       306114
29   108827166              Internet privacy       273303
30   173608175            Parallel computing       233645
31      459310         Computational science        96421
32   118524514         Computer architecture        83974
33   113775141          Computer engineering        79167